### ISSUE TITLE
Patchwork times out when trying to use my invite code

### ISSUE THREAD

**Issue by voodoohop** [staltz/easy-ssb-pub#10]
So patchwork gives me a "could not connect to sbot" error after quite a long wait. I get my invite code from the running easy-ssb-pub server here: http://104.236.242.204/

How can I go about investigating this issue? I'm getting some 404 request errors on the server command-line log.

when I try to run "sbot" from the command-line I get 
```
Error: no manifest file- should be generated first time server is run
    at U4cM2R8x+cHnwYSRW5Qytus89XrA9etJFg2mUXZ8UNw= (/usr/local/lib/node_modules/scuttlebot/sbot.js:37019:11)
    at Function.Module._load (module.js:439:3)
  Error: ENOENT: no such file or directory, open '/root/.ssb/manifest.json'
```

**Comment by voodoohop** [comment]
I just figured it out. a digital ocean firewall problem:

```
*** System restart required ***
-------------------------------------------------------------------------------
Thank you for using DigitalOcean's NodeJS Application

The "ufw" firewall is enabled. All ports except for 22, 80, and 443 are BLOCKED

-------------------------------------------------------------------------------
```
