### ISSUE TITLE
Easy-SSB-Pub in Centos 7

### ISSUE THREAD

**Issue by uhlhosting** [staltz/easy-ssb-pub#20]
Managed to deploy all dependencies up to this point:

`[root@pub easy-ssb-pub]# HOST=pub.cosmicsound.one npm start                                                                                                                               > easy-ssb-pub@4.0.0 start /root/easy-ssb-pub                                                > tsc && node dist/index --host $HOST --no-discovery                                                                                                                                      src/discovery.ts(113,3): error TS2322: Type 'Observable<{}>' is not assignable to type 'Observable<Response>'.                                                                              Type '{}' is not assignable to type 'Response'.                                                Property 'text' is missing in type '{}'.                                                 npm ERR! code ELIFECYCLE                                                                     npm ERR! errno 2                                                                             npm ERR! easy-ssb-pub@4.0.0 start: `tsc && node dist/index --host $HOST --no-discovery`      npm ERR! Exit status 2                                                                       npm ERR!                                                                                     npm ERR! Failed at the easy-ssb-pub@4.0.0 start script.                                      npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                                                                                                                                                                                     npm ERR! A complete log of this run can be found in:                                         npm ERR!     /root/.npm/_logs/2017-11-01T05_17_19_579Z-debug.log  `

**Comment by uhlhosting** [comment]
http://pub.cosmicsound.one/invited I get this:

```
TypeError: Cannot read property 'match' of undefined
   at Object.isPrivate (/usr/src/app/node_modules/scuttlebot/node_modules/ip/lib/ip.js:262:14)
   at Object.<anonymous> (/usr/src/app/node_modules/scuttlebot/plugins/invite.js:71:40)
   at apply (/usr/src/app/node_modules/muxrpc-validation/index.js:173:15)
   at Object.<anonymous> (/usr/src/app/node_modules/muxrpc-validation/index.js:82:14)
   at Object.hooked (/usr/src/app/node_modules/hoox/index.js:10:15)
   at /usr/src/app/dist/index.js:98:16
   at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
   at next (/usr/src/app/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by afincato** [comment]
+1 I get the same.

Just followed the instructions but changed from port `80:80` to be `90:80`

```
sudo docker run -e "HOST=se.rv.er.ip" -v $HOME/.ssb:/root/.ssb -p 90:80 -p 8008:8008 -p 8007:8007 -m 450M --memory-swap 1G --restart=unless-stopped --name ssb-pub -d staltz/easy-ssb-pub
```

then visiting `se.rv.er.ip:90`

when I click on Get an Invitation I have the error as above.

**Comment by uhlhosting** [comment]
afincato and why you closed it?

**Comment by afincato** [comment]
If you run the above command and change `run -e "HOST=se.rv.er.ip"` w/ ``run -e "PUB_URL =se.rv.er.ip"` it works!

```
sudo docker run -e "PUB_URL =se.rv.er.ip" -v $HOME/.ssb:/root/.ssb -p 90:80 -p 8008:8008 -p 8007:8007 -m 450M --memory-swap 1G --restart=unless-stopped --name ssb-pub -d staltz/easy-ssb-pub
```
