### ISSUE TITLE
Invitation gives error

### ISSUE THREAD

**Issue by schollz** [staltz/easy-ssb-pub#21]
Hi, I've got the server running: https://ssb.yakczar.com/.

However, the invites don't work, it gives the following error:

```
TypeError: Cannot read property 'match' of undefined
   at Object.isPrivate (/usr/src/app/node_modules/scuttlebot/node_modules/ip/lib/ip.js:262:14)
   at Object.<anonymous> (/usr/src/app/node_modules/scuttlebot/plugins/invite.js:71:40)
   at apply (/usr/src/app/node_modules/muxrpc-validation/index.js:173:15)
   at Object.<anonymous> (/usr/src/app/node_modules/muxrpc-validation/index.js:82:14)
   at Object.hooked (/usr/src/app/node_modules/hoox/index.js:10:15)
   at /usr/src/app/dist/index.js:98:16
   at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
   at next (/usr/src/app/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5) 
```

I'm running using the version from Docker hub.

**Comment by schollz** [comment]
Aw, figured it out.

I had to use `-e "PUB_URL=ssb.yakczar.com"` instead of  `-e "HOST=ssb.yakczar.com"`.

**Comment by afincato** [comment]
This worked! See #20.
