### ISSUE TITLE
easy-ssb-pub not starting

### ISSUE THREAD

**Issue by arcfide** [staltz/easy-ssb-pub#31]
I'm getting the following error in my log outputs when trying to start easy-ssb-pub:

flumelog-offset: blockSize and codec params moved into an object. https://github.com/flumedb/flumelog-offset
Log level: notice
RELOAD INDEX: {"version":13,"since":1521531478395.003}
RELOAD INDEX: {"version":5,"since":1521531477458.0176}
LOAD LINKS SINCE null 1521531477458.0176
./usr/src/app/node_modules/bytewise-core/util.js:26
    throw new TypeError(message)
    ^

TypeError: Unknown value
    at util.assert (/usr/src/app/node_modules/bytewise-core/util.js:26:11)
    at Object.bytewise.encode (/usr/src/app/node_modules/bytewise-core/index.js:69:3)
    at Object.util.encodeList [as encode] (/usr/src/app/node_modules/bytewise-core/util.js:145:23)
    at serialize (/usr/src/app/node_modules/bytewise-core/index.js:23:22)
    at Object.bytewise.encode (/usr/src/app/node_modules/bytewise-core/index.js:60:18)
    at Object.util.encodeList [as encode] (/usr/src/app/node_modules/bytewise-core/util.js:145:23)
    at serialize (/usr/src/app/node_modules/bytewise-core/index.js:23:22)
    at Object.bytewise.encode (/usr/src/app/node_modules/bytewise-core/index.js:60:18)
    at Codec.encodeKey (/usr/src/app/node_modules/level-packager/node_modules/level-codec/index.js:30:45)
    at /usr/src/app/node_modules/level-packager/node_modules/level-codec/index.js:51:17
n

**Comment by arcfide** [comment]
I'm also seeing a lot of this in my log:

server error, from net:::ffff:122.100.163.46:36018~shs:
Error: wrong number
    at abort (/usr/src/app/node_modules/secret-handshake/protocol.js:80:45)
    at Object.cb (/usr/src/app/node_modules/secret-handshake/protocol.js:93:20)
    at drain (/usr/src/app/node_modules/pull-reader/index.js:39:14)
    at more (/usr/src/app/node_modules/pull-reader/index.js:51:13)
    at /usr/src/app/node_modules/pull-reader/index.js:62:9
    at /usr/src/app/node_modules/pull-reader/index.js:20:7
    at /usr/src/app/node_modules/pull-stream/throughs/through.js:19:9
    at drain (/usr/src/app/node_modules/stream-to-pull-stream/index.js:141:18)
    at Socket.<anonymous> (/usr/src/app/node_modules/stream-to-pull-stream/index.js:150:5)
    at emitOne (events.js:116:13)
